[PHP]
display_errors=Off
display_startup_errors=Off
log_errors=On
error_log=""
short_open_tag = true

[xdebug]
zend_extension=xdebug
xdebug.mode=debug
xdebug.client_port=9003
xdebug.client_host=127.0.0.1
xdebug.start_with_request=yes
